- name: Create private key for CA
  local_action:
    module: community.crypto.openssl_privatekey
    path: ./ca.key
    passphrase: "{{ secret_ca_passphrase }}"
    cipher: auto
    mode: 0644
- name: Create certificate signing request (CSR) for CA certificate
  local_action:
    module: community.crypto.openssl_csr_pipe
    privatekey_path: ./ca.key
    privatekey_passphrase: "{{ secret_ca_passphrase }}"
    common_name: Ansible CA
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr
- name: Create self-signed CA certificate from CSR
  local_action:
    module: community.crypto.x509_certificate
    path: ./ca.pem
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: ./ca.key
    privatekey_passphrase: "{{ secret_ca_passphrase }}"
    provider: selfsigned

