- name: Configure hub admin user and execution profile via the Hub API
  block:
    - name: Get hub admin user id
      ansible.builtin.uri:
        url: https://localhost:{{ ingress_port | default('9090', true) }}/api/v2/auth/me
        user: "{{admin.username}}"
        password: "{{admin.password}}"
        force_basic_auth: true
        validate_certs: no
        body_format: json
        return_content: true
      register: hub_res
      until: hub_res.status | default(0) == 200
      retries: 30
      delay: 2

    - name: Configure the hub admin default linux username and home directory
      ansible.builtin.uri:
        url: https://localhost:{{ ingress_port | default('9090', true) }}/api/v2/auth/users/{{hub_res.json._id}}
        method: PATCH
        user: "{{admin.username}}"
        password: "{{admin.password}}"
        force_basic_auth: true
        validate_certs: no
        body_format: json
        headers:
          Content-Type: "application/json-patch+json"
        body: |-
          [
            { "op": "add", "path": "/firstName", "value": "Hub" },
            { "op": "add", "path": "/lastName", "value": "Administrator" },
            { "op": "add", "path": "/displayName", "value": "Hub Administrator" },
            { "op": "add", "path": "/unixHomeDirectory", "value": "{{ admin.linux_home_dir }}" },
            { "op": "add", "path": "/unixUserName", "value": "{{ admin.linux_username }}" }
          ]
      when: "(hub_res.json['unixUserName'] is not defined)"

    - name: Get hub excecution profile id
      ansible.builtin.uri:
        url: https://localhost:{{ ingress_port | default('9090', true) }}/api/v2/execution-profiles/execprofiles?filter[name][EQ]=Standard
        user: "{{admin.username}}"
        password: "{{admin.password}}"
        force_basic_auth: true
        validate_certs: no
        body_format: json
        return_content: true
      register: hub_execution_profile_res

    - name: Configure the hub environment settings
      ansible.builtin.uri:
        url: https://localhost:{{ ingress_port | default('9090', true) }}/api/v2/execution-profiles/execprofiles/{{hub_execution_profile_res.json.data[0]._id}}
        method: PATCH
        user: "{{admin.username}}"
        password: "{{admin.password}}"
        force_basic_auth: true
        validate_certs: no
        body_format: json
        headers:
          Content-Type: "application/json-patch+json"
        body: |-
          [{ "op": "add", "path": "/", "value": "environment"},
           { "op": "add", "path": "/environment", "value": { "PYTHONLIB": "/usr/lib64/libpython3.6m.so.1.0" }},
           { "op": "add", "path": "/environment/R_HOME", "value":"/usr/lib64/R/"},
           { "op": "add", "path": "/properties/directoryShortcuts", "value": { "/Shared": "/shared_store/{user_id}" }},
           { "op": "add", "path": "/properties/intermediateFilesDir", "value":"/shared_store/{user_id}/imfiles"}]
      register: exec_profile_result
      failed_when: "exec_profile_result.status not in [200, 403]"
