- hosts: all
  become: yes
  vars_files:
    - vars/ldap.yaml
    - vars/common.yaml
  vars:
    wps_rpm: "wps-5.0.0.3.2142_ea3_release-1.x86_64.rpm"
    worker_rpm: "swhub-worker"
    hub_rpm: "swhub"
    bootstrap_params: "{{ '--nointernaltls' if ca_certs != 'internal' else ''}}"
  tasks:
  - name: Configure tasks
    ansible.builtin.include_tasks: configure_tasks.yaml
