- hosts: all
  become: yes
  vars_files:
    - vars/ldap.yaml
    - vars/common.yaml
    - vars/license.yaml
  vars:
    slc_rpm: "altairslc2024"
    worker_rpm: "slchub-worker"
    hub_rpm: "slchub"
    bootstrap_params: "{{ '--nointernaltls' if ca_certs != 'internal' else ''}}"
  tasks:
    - name: Worker optional components
      ansible.builtin.include_tasks: worker_optional.yaml
      when: "'workers' in group_names"

