- hosts: all
  become: yes
  vars_files:
    - vars/ldap.yaml
    - vars/common.yaml
    - vars/license.yaml
  vars:
    slc_rpm: "altairslc2024"
    worker_rpm: "slchub-worker"
    hub_rpm: "slchub"
    airgapped: # Optional:
      slc_rpm_file: altairslc-5.24.0.3.564_ea3_release-1.x86_64.rpm
      worker_rpm_file: slchub-worker-2023.4.0-1_x86_64.rpm
      hub_rpm_file: slchub-2023.4.0-1_x86_64.rpm
    bootstrap_params: "{{ '--nointernaltls' if ca_certs != 'internal' else ''}}"
  tasks:
  - name: Install tasks
    ansible.builtin.include_tasks: install_tasks.yaml
  - name: Configure tasks
    ansible.builtin.include_tasks: configure_tasks.yaml
