- hosts: all
  become: yes
  vars_files:
    - vars/ldap.yaml
    - vars/common.yaml
  vars:
    wps_rpm: "wps-5.0.0.2.1163_ea2_maintenance-1.x86_64.rpm"
    worker_rpm: "wpshub-worker"
    hub_rpm: "wpshub"
    bootstrap_params: "{{ '--nointernaltls' if ca_certs != 'internal' else ''}}"
  tasks:
  - name: Install tasks
    ansible.builtin.include_tasks: install_tasks.yaml
