- hosts: all
  become: yes
  vars_files:
    - vars/ldap.yaml
    - vars/common.yaml
  vars:
    wps_rpm: "wps-4.4.1.0.5212_ga_prerelease-1.x86_64.rpm"
    worker_rpm: "wpshub-worker"
    hub_rpm: "wpshub"
    bootstrap_params: "{{ '--nointernaltls' if ca_certs != 'internal' else ''}}"
  tasks:
  - name: Configure tasks
    ansible.builtin.include_tasks: configure_tasks.yaml
