  - name: Create a PostgreSQL group
    ansible.builtin.group:
      name: hub-postgresql
      state: present

  - name: Create a PostgreSQL user
    ansible.builtin.user:
      name: hub-postgresql
      groups: hub-postgresql
      state: present
      system: yes

  - name: Create PostgreSQL directory
    ansible.builtin.file:
      path: /opt/postgresql
      state: directory
      owner: hub-postgresql
      group: hub-postgresql
      mode: '0755'

  - name: Copy RPMs
    ansible.builtin.copy:
      src: "rpms/{{ item }}"
      dest: "/opt/postgresql"
      owner: hub-postgresql
      group: hub-postgresql
      mode: '0755'
    with_items:
      - postgresql13-server-13.7-1PGDG.rhel8.x86_64.rpm
      - postgresql13-13.7-1PGDG.rhel8.x86_64.rpm
      - postgresql13-libs-13.7-1PGDG.rhel8.x86_64.rpm

  - name: Install PostgreSQL libs RPM
    ansible.builtin.yum:
      name: /opt/postgresql/postgresql13-libs-13.7-1PGDG.rhel8.x86_64.rpm
      state: present
      disable_gpg_check: True
  - name: Install PostgreSQL RPM
    ansible.builtin.yum:
      name: /opt/postgresql/postgresql13-13.7-1PGDG.rhel8.x86_64.rpm
      state: present
      disable_gpg_check: True
  - name: Install PostgreSQL server RPM
    ansible.builtin.yum:
      name: /opt/postgresql/postgresql13-server-13.7-1PGDG.rhel8.x86_64.rpm
      state: present
      disable_gpg_check: True
  - name: Initialize the database
    ansible.builtin.command: /usr/pgsql-13/bin/postgresql-13-setup initdb
    ignore_errors: yes

  - name: Start the database
    ansible.builtin.command: systemctl start postgresql-13

  - name: Enable the database
    ansible.builtin.command: systemctl enable postgresql-13

  - name: Create PostgreSQL configuration
    ansible.builtin.template:
      src: templates/pg_hba.conf.j2
      dest: /var/lib/pgsql/13/data/pg_hba.conf
      mode: 0644

  - name: Create PostgreSQL configuration
    ansible.builtin.template:
      src: templates/postgresql.conf.j2
      dest: /var/lib/pgsql/13/data/postgresql.conf
      mode: 0644

  - name: Restart PostgreSQL
    ansible.builtin.command: systemctl restart postgresql-13

  - name: Create postgres hub user
    ansible.builtin.command: sudo runuser -l postgres -c "psql -d postgres -c \"CREATE USER {{db_user}} WITH PASSWORD '{{db_password}}';\""
    ignore_errors: yes

  - name: Create postgres hub database
    ansible.builtin.command: sudo runuser -l postgres -c "psql -d postgres -c \"create database {{db_name}};  \""
    ignore_errors: yes

  - name: Grant access to hub database user
    ansible.builtin.command: sudo runuser -l postgres -c "psql -d postgres -c \" GRANT CONNECT ON DATABASE {{db_name}} TO {{db_user}}; GRANT ALL ON DATABASE {{db_name}} to {{db_user}}; GRANT ALL ON ALL SEQUENCES IN SCHEMA PUBLIC TO {{db_user}}; GRANT ALL ON ALL FUNCTIONS IN SCHEMA PUBLIC TO {{db_user}}; ALTER DATABASE {{db_name}} OWNER TO {{db_user}};  \" "
    ignore_errors: yes




