- name: Install createrepo
  yum:
    name: "createrepo"
    state: latest
- name: Make rpms dir
  file:
    path: "{{ rpmsdirectory }}"
    state: directory
- name: Copy rpms
  ansible.builtin.copy:
    src: "rpms/{{ item }}"
    dest: "{{ rpmsdirectory }}/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - wpshub-0.0.11-2.x86_64.rpm
    - wpshub-auth-1.5.2-2.x86_64.rpm
    - wpshub-base-0.0.6-2.x86_64.rpm
    - wpshub-ca-1.1.5-2.x86_64.rpm
    - wpshub-ca-worker-1.1.5-2.x86_64.rpm
    - wpshub-config-0.0.11-2.x86_64.rpm
    - wpshub-configtmpl-1.1.5-2.x86_64.rpm
    - wpshub-data-access-1.4.0-2.x86_64.rpm
    - wpshub-docs-1.2.2-2.x86_64.rpm
    - wpshub-envoy-1.0.2-2.x86_64.rpm
    - wpshub-hubctl-1.3.2-2.x86_64.rpm
    - wpshub-ingressctrl-1.11.2-2.x86_64.rpm
    - wpshub-link-server-1.24.3-2.x86_64.rpm
    - wpshub-management-1.3.2-2.x86_64.rpm
    - wpshub-minio-cfg-1.1.4-2.x86_64.rpm
    - wpshub-namespaces-1.1.1-2.x86_64.rpm
    - wpshub-nats-v2.4.0-2.x86_64.rpm
    - wpshub-nginx-1.20.1-2.x86_64.rpm
    - wpshub-nomad-plugin-1.2.2-2.x86_64.rpm
    - wpshub-nomad-v1.2.4-2.x86_64.rpm
    - wpshub-ondemand-api-1.11.2-2.x86_64.rpm
    - wpshub-pipeline-cli-1.7.2-2.x86_64.rpm
    - wpshub-pipelines-1.7.2-2.x86_64.rpm
    - wpshub-portal-0.1.229-2.x86_64.rpm
    - wpshub-postgres-1.1.3-2.x86_64.rpm
    - wpshub-postgres-repo-1.1.3-2.x86_64.rpm
    - wpshub-rbac-1.3.2-2.x86_64.rpm
    - wpshub-webdav-0.0.63-2.x86_64.rpm
    - wpshub-worker-0.0.11-2.x86_64.rpm
    - wpshub-worker-config-0.0.11-2.x86_64.rpm
- name: Copy WPS rpm
  ansible.builtin.copy:
    src: "rpms/{{ item }}"
    dest: "{{ rpmsdirectory }}/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "{{ wps_rpm }}"
  when: "'workers' in group_names"
- name: Create repo index
  ansible.builtin.shell: "createrepo --basedir={{ rpmsdirectory }} {{ rpmsdirectory }}"
- name: Add repo local
  yum_repository:
    name: local
    description: "Repo for local files"
    baseurl: "file://{{ rpmsdirectory }}"
    gpgcheck: no
