- name: Install createrepo
  yum:
    name: "createrepo"
    state: latest
- name: Make rpms dir
  file:
    path: "{{ rpmsdirectory }}"
    state: directory
- name: Copy rpms
  ansible.builtin.copy:
    src: "rpms/{{ item }}"
    dest: "{{ rpmsdirectory }}/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - swhub_2.0.22.448-1_x86_64.rpm
    - swhub-worker_2.0.22.448-1_x86_64.rpm
- name: Copy SLC rpm
  ansible.builtin.copy:
    src: "rpms/{{ item }}"
    dest: "{{ rpmsdirectory }}/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "{{ wps_rpm }}"
  when: "'workers' in group_names"
- name: Create repo index
  ansible.builtin.shell: "createrepo --basedir={{ rpmsdirectory }} {{ rpmsdirectory }}"
- name: Add repo local
  yum_repository:
    name: local
    description: "Repo for local files"
    baseurl: "file://{{ rpmsdirectory }}"
    gpgcheck: no
