  - name: Create a seaweedfs group
    ansible.builtin.group:
      name: hub-seaweedfs
      state: present

  - name: Create a seaweedfs user
    ansible.builtin.user:
      name: hub-seaweedfs
      groups: hub-seaweedfs
      state: present
      system: yes

  - name: Create SeaweedFS data directory
    ansible.builtin.file:
      path: /var/seaweedfs/data
      state: directory
      owner: hub-seaweedfs
      group: hub-seaweedfs
      mode: '0755'

  - name: Create SeaweedFS directory
    ansible.builtin.file:
      path: /opt/seaweedfs
      state: directory
      owner: hub-seaweedfs
      group: hub-seaweedfs
      mode: '0755'

  - name: Copy TAR
    ansible.builtin.copy:
      src: "rpms/{{ item }}"
      dest: "/opt/seaweedfs"
      owner: hub-seaweedfs
      group: hub-seaweedfs
      mode: '0755'
    with_items:
      - linux_amd64.tar.gz

  - name: Extract archive
    ansible.builtin.unarchive:
      src: /opt/seaweedfs/linux_amd64.tar.gz
      dest: /opt/seaweedfs
      remote_src: yes

  - name: Create seaweedfs configuration
    ansible.builtin.template:
      src: templates/seaweedfs_config.json.j2
      dest: /opt/seaweedfs/config.json
      mode: 0644
  - name: Recursively change ownership of a directory
    ansible.builtin.file:
      path: /opt/seaweedfs
      state: directory
      recurse: yes
      owner: hub-seaweedfs
      group: hub-seaweedfs
  - name: Recursively change ownership of a directory
    ansible.builtin.file:
      path: /var/seaweedfs
      state: directory
      recurse: yes
      owner: hub-seaweedfs
      group: hub-seaweedfs


  - name: Create s3 bucket
    ansible.builtin.command: echo "s3.bucket.create -name {{s3_bucket}}" | sudo /opt/seaweedfs/weed shell

  - name: create seaweedfs service
    ansible.builtin.template:
      src: templates/hub-seaweedfs.service.j2
      dest: /etc/systemd/system/hub-seaweedfs.service

  - name: Start seaweedfs service
    ansible.builtin.command: systemctl start hub-seaweedfs

  - name: enable seaweedfs service
    ansible.builtin.command: systemctl enable hub-seaweedfs
